### ISSUE TITLE
More info required in the readme

### ISSUE THREAD

**Issue by malhal** [facebook/FBFetchedResultsController#12]
About what your problem was using NSFetchedResultsController with parent/child contexts. I'm not aware of any problems.

**Comment by adamjernst** [comment]
Good point, it's underspecified. It is a bug that results in deadlock. If you're not encountering it, great! No need to use this. For all I know it's fixed in later versions of iOS.

We don't use Core Data at Facebook any more, so unfortunately we don't have the context to fill in here.
